[project]
name = "solid-fastapi-template"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "pandas>=2.3.3",
    "polars>=1.35.1",
    "pytest>=8.4.2",
    "uvicorn>=0.38.0",
]
